#!/usr/bin/env bash
# This script configures the /etc/hosts file to change the resolution of localhost and facebook.com.

cp /etc/hosts /etc/hosts.bak

sed -i '/127.0.0.1 localhost/d' /etc/hosts
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Configuración completada. Las entradas se han actualizado en /etc/hosts."
